name: Cameras
favicon: null
layout_spectrum: 0.8636
typography_spectrum: 0.3905068861786276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#24202f'
    - '#ffffff'
    - '#4d5061'
    - '#dedce5'
  brandStrength: 0
  lightness: 0.2845285285729915
  saturation: 0.02959201275371015
  rhythmicContrast: 0.5281425334978849
purpose: []
