typography_spectrum: 0.3905068861786276
style: the-composer
color:
  brandColors:
    - '#000000'
    - '#24202f'
    - '#ffffff'
    - '#4d5061'
    - '#dedce5'
  brandStrength: 0
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8636
analytics:
  google: null
  facebook: null
  twitter: null
name: Cameras
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
